# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-05 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
        migrations.AddField(
            model_name='address',
            name='email',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='address',
            name='first_name',
            field=models.CharField(default='Judd', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='last_name',
            field=models.CharField(default='Arias', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('billing', 'Billing'), ('shipping', 'Shipping')], default='billing', max_length=20),
        ),
        migrations.AlterField(
            model_name='address',
            name='extended_address',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
