# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-12 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_address_same'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='default_address',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('billing', 'Billing'), ('shipping', 'Shipping')], default='shipping', max_length=20),
        ),
    ]
