# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-17 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_auto_20170112_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='brain_tree_code',
            field=models.CharField(default='AZ', max_length=2),
            preserve_default=False,
        ),
    ]
