# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0005_address_brain_tree_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='brain_tree_code',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
