# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-30 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0006_auto_20170126_0135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=120, unique=True)),
                ('braintree_id', models.CharField(max_length=120)),
            ],
        ),
    ]
