# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-31 18:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0007_guest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='braintree_id',
        ),
    ]
