# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-19 19:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0008_remove_guest_braintree_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='brain_tree_code',
        ),
        migrations.RemoveField(
            model_name='address',
            name='same',
        ),
    ]
