# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20170315_0414'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=19.99, max_digits=6),
            preserve_default=False,
        ),
    ]
