# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-07 01:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_auto_20170707_0119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
