# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-14 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20170707_0135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='research',
            old_name='research_article',
            new_name='article',
        ),
        migrations.RenameField(
            model_name='research',
            old_name='research_title',
            new_name='product_effect',
        ),
        migrations.AddField(
            model_name='research',
            name='title',
            field=models.CharField(default='power output', max_length=120),
            preserve_default=False,
        ),
    ]
