# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-14 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_auto_20170814_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='product',
            field=models.CharField(max_length=120),
        ),
    ]
