# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-14 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_auto_20170814_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
