# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-14 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_auto_20170814_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='article',
            field=models.CharField(max_length=300),
        ),
        migrations.RemoveField(
            model_name='research',
            name='product_effect',
        ),
        migrations.AddField(
            model_name='research',
            name='product_effect',
            field=models.ManyToManyField(to='products.Benefit'),
        ),
    ]
